import Head from "next/head";

import Movies from "../components/Movies";
import Banner from "../components/Banner";
import Navbar from "../components/Navbar";
import Footer from "../components/common/Footer";

import api from "../apisauceInstance";
import { requests } from "../requests";
import { formatCategoryName, pickRandomMovie } from "../utils";
import { useState, useEffect } from "react";

export default function Home({ movies }) {
  const [bannerMovie, setBannerMovie] = useState(null);

  useEffect(() => {
    setBannerMovie(pickRandomMovie(movies));

    // TODO: Implement this the right way
    // setInterval(() => {
    //   setBannerMovie(pickRandomMovie(movies));
    // }, 9000);
  }, []);

  return (
    <>
      <Head>
        <title>Netflix Clone by Sep Motameni</title>
        <meta name="description" content="Netflix Clone by Sep Motameni" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen bg-[#141414]">
        <Navbar />
        {bannerMovie && (
          <div className="">
            <Banner movie={bannerMovie} />
          </div>
        )}
        <Movies movies={movies} />
      </main>
      {/* TODO: Do cool animation that moves around page for footer */}
      <Footer />
    </>
  );
}

// TODO: List
// * Modal for movie details
// * Row Component
// * State for my list
// * Sign in page
// * Netflix intro animation
// * Skeleton

// TODO: Too much data being passed to the component.
// https://nextjs.org/docs/messages/large-page-data
export async function getServerSideProps(context) {
  // const obj = {};

  // for (let request in requests) {
  //   let categoryName = formatCategoryName(request);

  //   const { data } = await api.get(requests[request]);
  //   obj[categoryName] = data.results;
  // }

  return {
    props: {
      movies: {
        Trending: [
          {
            origin_country: ["US"],
            id: 92782,
            backdrop_path: "/rlCRM7U5g2hcU1O8ylGcqsMYHIP.jpg",
            genre_ids: [10765, 10759, 35],
            vote_count: 133,
            first_air_date: "2022-06-08",
            original_language: "en",
            overview:
              "A great student, avid gamer, and voracious fan-fic scribe, Kamala Khan has a special affinity for superheroes, particularly Captain Marvel. However, she struggles to fit in at home and at school — that is, until she gets superpowers like the heroes she’s always looked up to. Life is easier with superpowers, right?",
            poster_path: "/cdkyMYdu8ao26XOBvilNzLneUg1.jpg",
            name: "Ms. Marvel",
            vote_average: 8,
            original_name: "Ms. Marvel",
            popularity: 2238.535,
            media_type: "tv",
          },
          {
            original_name: "Obi-Wan Kenobi",
            id: 92830,
            overview:
              "During the reign of the Galactic Empire, former Jedi Master, Obi-Wan Kenobi, embarks on a crucial mission to confront allies turned enemies and face the wrath of the Empire.",
            vote_count: 310,
            backdrop_path: "/8H64YmIYxpRJgSTuLUGRUSyi2kN.jpg",
            vote_average: 8,
            genre_ids: [10765, 10759, 18],
            name: "Obi-Wan Kenobi",
            original_language: "en",
            first_air_date: "2022-05-26",
            poster_path: "/qJRB789ceLryrLvOKrZqLKr2CGf.jpg",
            origin_country: ["US"],
            popularity: 1945.937,
            media_type: "tv",
          },
          {
            overview:
              "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
            first_air_date: "2016-07-15",
            backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
            id: 66732,
            genre_ids: [10765, 18, 9648],
            original_language: "en",
            original_name: "Stranger Things",
            origin_country: ["US"],
            name: "Stranger Things",
            vote_count: 10969,
            vote_average: 8.6,
            poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
            popularity: 2909.727,
            media_type: "tv",
          },
          {
            genre_ids: [10765, 10759],
            original_language: "en",
            first_air_date: "2019-07-25",
            poster_path: "/stTEycfG9928HYGEISBFaG1ngjM.jpg",
            original_name: "The Boys",
            origin_country: ["US"],
            name: "The Boys",
            overview:
              "A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.",
            vote_count: 6050,
            vote_average: 8.4,
            backdrop_path: "/n6vVs6z8obNbExdD3QHTr4Utu1Z.jpg",
            id: 76479,
            popularity: 4278.866,
            media_type: "tv",
          },
          {
            original_language: "en",
            original_title: "Spiderhead",
            poster_path: "/7COPO5B9AOKIB4sEkvNu0wfve3c.jpg",
            video: false,
            vote_average: 6.2,
            overview:
              "A prisoner in a state-of-the-art penitentiary begins to question the purpose of the emotion-controlling drugs he's testing for a pharmaceutical genius.",
            release_date: "2022-06-15",
            vote_count: 41,
            id: 615469,
            adult: false,
            backdrop_path: "/5tmjv1moohN65IuHAbYjKw3cw7I.jpg",
            title: "Spiderhead",
            genre_ids: [878, 53],
            popularity: 73.854,
            media_type: "movie",
          },
          {
            vote_count: 576,
            id: 507086,
            adult: false,
            backdrop_path: "/wo3l9p0S7pcvwlzlndtKgq0peRJ.jpg",
            genre_ids: [28, 12, 878],
            title: "Jurassic World Dominion",
            original_language: "en",
            original_title: "Jurassic World Dominion",
            poster_path: "/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
            release_date: "2022-06-01",
            video: false,
            vote_average: 6.7,
            overview:
              "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.",
            popularity: 2440.155,
            media_type: "movie",
          },
          {
            genre_ids: [14, 12, 28],
            original_language: "en",
            original_title: "Fantastic Beasts: The Secrets of Dumbledore",
            poster_path: "/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg",
            video: false,
            vote_average: 6.9,
            overview:
              "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.",
            release_date: "2022-04-06",
            vote_count: 1824,
            title: "Fantastic Beasts: The Secrets of Dumbledore",
            adult: false,
            backdrop_path: "/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg",
            id: 338953,
            popularity: 3670.155,
            media_type: "movie",
          },
          {
            poster_path: "/fVf4YHHkRfo1uuljpWBViEGmaUQ.jpg",
            video: false,
            vote_average: 7.8,
            overview:
              "After discovering a once-in-a-lifetime player with a rocky past abroad, a down on his luck basketball scout takes it upon himself to bring the phenom to the States without his team's approval. Against the odds, they have one final shot to prove they have what it takes to make it in the NBA.",
            release_date: "2022-06-03",
            vote_count: 503,
            adult: false,
            backdrop_path: "/hGr0FrLI74vqpBWTBOPloDBwOAK.jpg",
            id: 705861,
            genre_ids: [18, 35],
            title: "Hustle",
            original_language: "en",
            original_title: "Hustle",
            popularity: 1325.419,
            media_type: "movie",
          },
          {
            adult: false,
            backdrop_path: "/m0YjB4VfghKey8Ppsmz8qCd0v1m.jpg",
            genre_ids: [28, 35, 80],
            original_language: "en",
            original_title: "The Unbearable Weight of Massive Talent",
            poster_path: "/aqhLeieyTpTUKPOfZ3jzo2La0Mq.jpg",
            video: false,
            vote_average: 7.2,
            vote_count: 280,
            overview:
              "Creatively unfulfilled and facing financial ruin, Nick Cage must accept a $1 million offer to attend the birthday of a dangerous superfan. Things take a wildly unexpected turn when Cage is recruited by a CIA operative and forced to live up to his own legend, channeling his most iconic and beloved on-screen characters in order to save himself and his loved ones.",
            release_date: "2022-04-20",
            title: "The Unbearable Weight of Massive Talent",
            id: 648579,
            popularity: 2219.182,
            media_type: "movie",
          },
          {
            genre_ids: [28, 18],
            original_language: "en",
            original_title: "Top Gun: Maverick",
            poster_path: "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
            video: false,
            vote_average: 8.3,
            overview:
              "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
            release_date: "2022-05-24",
            vote_count: 1072,
            title: "Top Gun: Maverick",
            adult: false,
            backdrop_path: "/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
            id: 361743,
            popularity: 939.559,
            media_type: "movie",
          },
          {
            adult: false,
            backdrop_path: "/kmCBLNHsNnlDEtghSaF2nabpG2T.jpg",
            genre_ids: [28, 878, 14],
            original_language: "en",
            original_title: "Morbius",
            poster_path: "/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg",
            video: false,
            title: "Morbius",
            vote_count: 1688,
            overview:
              "Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.",
            id: 526896,
            vote_average: 6.4,
            release_date: "2022-03-30",
            popularity: 2905.395,
            media_type: "movie",
          },
          {
            vote_count: 2071,
            id: 675353,
            adult: false,
            backdrop_path: "/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg",
            genre_ids: [28, 12, 10751, 35],
            title: "Sonic the Hedgehog 2",
            original_language: "en",
            original_title: "Sonic the Hedgehog 2",
            poster_path: "/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
            release_date: "2022-03-30",
            video: false,
            vote_average: 7.7,
            overview:
              "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.",
            popularity: 3268.177,
            media_type: "movie",
          },
          {
            genre_ids: [80, 9648, 53],
            original_language: "en",
            original_title: "The Batman",
            poster_path: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
            video: false,
            vote_average: 7.8,
            vote_count: 5183,
            overview:
              "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
            release_date: "2022-03-01",
            title: "The Batman",
            id: 414906,
            adult: false,
            backdrop_path: "/xHrp2pq73oi9D64xigPjWW1wcz1.jpg",
            popularity: 1588.662,
            media_type: "movie",
          },
          {
            adult: false,
            backdrop_path: "/i2tcQ9nDJpdJELPA82eCd7Irasd.jpg",
            genre_ids: [28, 53, 12],
            original_language: "en",
            original_title: "Interceptor",
            id: 831946,
            vote_count: 258,
            video: false,
            vote_average: 6.3,
            title: "Interceptor",
            overview:
              "A U.S. Army Captain uses her years of tactical training to save humanity from sixteen nuclear missiles launched at the U.S. as a violent attack threatens her remote missile interceptor station.",
            release_date: "2022-05-26",
            poster_path: "/cpWUtkcgRKeauhTyVMjYHxAutp4.jpg",
            popularity: 1718.981,
            media_type: "movie",
          },
          {
            vote_count: 2291,
            id: 453395,
            adult: false,
            backdrop_path: "/gUNRlH66yNDH3NQblYMIwgZXJ2u.jpg",
            genre_ids: [14, 28, 12],
            title: "Doctor Strange in the Multiverse of Madness",
            original_language: "en",
            original_title: "Doctor Strange in the Multiverse of Madness",
            poster_path: "/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
            release_date: "2022-05-04",
            video: false,
            vote_average: 7.4,
            overview:
              "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
            popularity: 2414.653,
            media_type: "movie",
          },
          {
            adult: false,
            backdrop_path: "/tqUD26YGjKmFqOJAgbNBah1gX0N.jpg",
            genre_ids: [16, 878, 12, 28, 10751],
            original_language: "en",
            original_title: "Lightyear",
            poster_path: "/vpILbP9eOQEtdQgl4vgjZUNY07r.jpg",
            video: false,
            title: "Lightyear",
            vote_count: 56,
            overview:
              "Legendary Space Ranger Buzz Lightyear embarks on an intergalactic adventure alongside a group of ambitious recruits and his robot companion Sox.",
            id: 718789,
            vote_average: 6.9,
            release_date: "2022-06-15",
            popularity: 926.726,
            media_type: "movie",
          },
          {
            genre_ids: [28, 12, 878],
            original_language: "en",
            original_title: "Everything Everywhere All at Once",
            poster_path: "/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
            video: false,
            title: "Everything Everywhere All at Once",
            vote_count: 661,
            overview:
              "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
            release_date: "2022-03-24",
            vote_average: 8.4,
            id: 545611,
            adult: false,
            backdrop_path: "/fIwiFha3WPu5nHkBeMQ4GzEk0Hv.jpg",
            popularity: 237.194,
            media_type: "movie",
          },
          {
            video: false,
            id: 634649,
            overview:
              "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
            release_date: "2021-12-15",
            adult: false,
            backdrop_path: "/ocUp7DJBIc8VJgLEw1prcyK1dYv.jpg",
            vote_count: 13554,
            genre_ids: [28, 12, 878],
            vote_average: 8.1,
            original_language: "en",
            original_title: "Spider-Man: No Way Home",
            poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
            title: "Spider-Man: No Way Home",
            popularity: 2014.174,
            media_type: "movie",
          },
          {
            overview:
              "Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy's mother. Two decades later, Amleth is now a Viking who's on a mission to save his mother, kill his uncle and avenge his father.",
            release_date: "2022-04-07",
            adult: false,
            backdrop_path: "/cqnVuxXe6vA7wfNWubak3x36DKJ.jpg",
            genre_ids: [28, 12, 14],
            vote_count: 1523,
            original_language: "en",
            original_title: "The Northman",
            poster_path: "/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg",
            vote_average: 7.3,
            video: false,
            title: "The Northman",
            id: 639933,
            popularity: 2306.858,
            media_type: "movie",
          },
          {
            overview:
              "The Crawley family goes on a grand journey to the South of France to uncover the mystery of the dowager countess's newly inherited villa.",
            release_date: "2022-04-27",
            adult: false,
            backdrop_path: "/nBHKT3pm5DmidZd5VS4bD5Hc2S3.jpg",
            id: 820446,
            genre_ids: [18, 10749],
            original_language: "en",
            original_title: "Downton Abbey: A New Era",
            poster_path: "/r5n4CLoIjUcnT3shWDi6MHdJ25a.jpg",
            vote_count: 107,
            video: false,
            vote_average: 7.4,
            title: "Downton Abbey: A New Era",
            popularity: 88.925,
            media_type: "movie",
          },
        ],
        Upcoming: [
          {
            adult: false,
            backdrop_path: "/tqUD26YGjKmFqOJAgbNBah1gX0N.jpg",
            genre_ids: [16, 878, 12, 28, 10751],
            id: 718789,
            original_language: "en",
            original_title: "Lightyear",
            overview:
              "Legendary Space Ranger Buzz Lightyear embarks on an intergalactic adventure alongside a group of ambitious recruits and his robot companion Sox.",
            popularity: 926.726,
            poster_path: "/vpILbP9eOQEtdQgl4vgjZUNY07r.jpg",
            release_date: "2022-06-15",
            title: "Lightyear",
            video: false,
            vote_average: 6.9,
            vote_count: 56,
          },
          {
            adult: false,
            backdrop_path: "/cugmVwK0N4aAcLibelKN5jWDXSx.jpg",
            genre_ids: [16, 28, 14, 12],
            id: 768744,
            original_language: "ja",
            original_title:
              "僕のヒーローアカデミア THE MOVIE ワールド ヒーローズ ミッション",
            overview:
              "A mysterious group called Humarize strongly believes in the Quirk Singularity Doomsday theory which states that when quirks get mixed further in with future generations, that power will bring forth the end of humanity. In order to save everyone, the Pro-Heroes around the world ask UA Academy heroes-in-training to assist them and form a world-classic selected hero team. It is up to the heroes to save the world and the future of heroes in what is the most dangerous crisis to take place yet in My Hero Academia.",
            popularity: 805.527,
            poster_path: "/4NUzcKtYPKkfTwKsLjwNt8nRIXV.jpg",
            release_date: "2021-08-06",
            title: "My Hero Academia: World Heroes' Mission",
            video: false,
            vote_average: 7.6,
            vote_count: 194,
          },
          {
            adult: false,
            backdrop_path: "/2gGVdr0BcKzma68SW2jpZfJtOlB.jpg",
            genre_ids: [10751, 16, 28, 12, 35],
            id: 438148,
            original_language: "en",
            original_title: "Minions: The Rise of Gru",
            overview:
              "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.",
            popularity: 412.243,
            poster_path: "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
            release_date: "2022-06-16",
            title: "Minions: The Rise of Gru",
            video: false,
            vote_average: 7.5,
            vote_count: 10,
          },
          {
            adult: false,
            backdrop_path: "/bcpATvKQmSgCbwxONs9PPQrer3A.jpg",
            genre_ids: [28, 12, 14],
            id: 616037,
            original_language: "en",
            original_title: "Thor: Love and Thunder",
            overview:
              "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now inexplicably wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
            popularity: 389.527,
            poster_path: "/4zLfBbGnuUBLbMVtagTZvzFwS8l.jpg",
            release_date: "2022-07-06",
            title: "Thor: Love and Thunder",
            video: false,
            vote_average: 0,
            vote_count: 0,
          },
          {
            adult: false,
            backdrop_path: "/geYUecpFI2AonDLhjyK9zoVFcMv.jpg",
            genre_ids: [16, 28, 12, 9648],
            id: 810693,
            original_language: "ja",
            original_title: "劇場版 呪術廻戦 0",
            overview:
              "Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won't leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enroll, but can he learn enough in time to confront the curse that haunts him?",
            popularity: 265.361,
            poster_path: "/3pTwMUEavTzVOh6yLN0aEwR7uSy.jpg",
            release_date: "2021-12-24",
            title: "Jujutsu Kaisen 0",
            video: false,
            vote_average: 7.9,
            vote_count: 187,
          },
          {
            adult: false,
            backdrop_path: "/klioTuA8JepFgV0EC7IxqV6VbrM.jpg",
            genre_ids: [27, 28, 53],
            id: 776797,
            original_language: "zh",
            original_title: "哭悲",
            overview:
              "A young couple is pushed to the limits of sanity as they attempt to be reunited amid the chaos of a pandemic outbreak. The streets erupt into violence and depravity, as those infected are driven to enact the most cruel and ghastly things imaginable.",
            popularity: 251.005,
            poster_path: "/a7VHvhROWorsWrtNKQnLZTxpxuG.jpg",
            release_date: "2021-01-22",
            title: "The Sadness",
            video: false,
            vote_average: 6.8,
            vote_count: 167,
          },
          {
            adult: false,
            backdrop_path: "/h9zyS1LrufwLI9FyhiPjPWsppEK.jpg",
            genre_ids: [27, 53],
            id: 756999,
            original_language: "en",
            original_title: "The Black Phone",
            overview:
              "Finney Shaw, a shy but clever 13-year-old boy, is abducted by a sadistic killer and trapped in a soundproof basement where screaming is of little use. When a disconnected phone on the wall begins to ring, Finney discovers that he can hear the voices of the killer’s previous victims. And they are dead set on making sure that what happened to them doesn’t happen to Finney.",
            popularity: 194.945,
            poster_path: "/iShDURqaP9Xhv9NBRkSpruxdgfQ.jpg",
            release_date: "2022-05-29",
            title: "The Black Phone",
            video: false,
            vote_average: 7.9,
            vote_count: 9,
          },
          {
            adult: false,
            backdrop_path: "/1zgz0LAT3avelWe6whHSa9j7zfq.jpg",
            genre_ids: [18, 10402, 36],
            id: 614934,
            original_language: "en",
            original_title: "Elvis",
            overview:
              "The life story of Elvis Presley as seen through the complicated relationship with his enigmatic manager, Colonel Tom Parker.",
            popularity: 119.506,
            poster_path: "/rva3UhKaMeiB0Vej5A2pm1leX7K.jpg",
            release_date: "2022-06-22",
            title: "Elvis",
            video: false,
            vote_average: 0,
            vote_count: 0,
          },
          {
            adult: false,
            backdrop_path: "/nV905JQSBo0a6zW8UmmmhDj0fQj.jpg",
            genre_ids: [80, 28, 53],
            id: 826749,
            original_language: "en",
            original_title: "Fortress",
            overview:
              "The story revolves around a top-secret resort for retired U.S. intelligence officers. A group of criminals led by Balzary breach the compound, hellbent on revenge on Robert, forcing the retired officer and his son to save the day.",
            popularity: 118.495,
            poster_path: "/vQxtoPJVfpHgL7DCg9hQFZKDWJa.jpg",
            release_date: "2021-12-17",
            title: "Fortress",
            video: false,
            vote_average: 6.2,
            vote_count: 222,
          },
          {
            adult: false,
            backdrop_path: "/ejkbJM697dNrtQvIiUpeUPGpoXX.jpg",
            genre_ids: [18],
            id: 632617,
            original_language: "en",
            original_title: "C'mon C'mon",
            overview:
              "Johnny and his young nephew forge a tenuous but transformational relationship when they embark on a cross-country trip to see life away from Los Angeles.",
            popularity: 66.118,
            poster_path: "/1oOyJsdcJnnE7cl9bZdUQvBjKNH.jpg",
            release_date: "2021-11-19",
            title: "C'mon C'mon",
            video: false,
            vote_average: 7.6,
            vote_count: 287,
          },
          {
            adult: false,
            backdrop_path: "/8Kbr2lV4XE2zqI564u0xlMLpx8r.jpg",
            genre_ids: [35, 878],
            id: 913814,
            original_language: "en",
            original_title: "Brian and Charles",
            overview:
              "An endearing outlier, Brian lives alone in a Welsh valley, inventing oddball contraptions that seldom work. After finding a discarded mannequin head, Brian gets an idea. Three days, a washing machine, and sundry spare parts later, he’s invented Charles, an artificially intelligent robot who learns English from a dictionary and proves a charming, cheeky companion. Before long, however, Charles also develops autonomy. Intrigued by the wider world — or whatever lies beyond the cottage where Brian has hidden him away — Charles craves adventure.",
            popularity: 31.237,
            poster_path: "/rH1S6THHYK6HMOxY0mwUIjBo3fk.jpg",
            release_date: "2022-06-17",
            title: "Brian and Charles",
            video: false,
            vote_average: 7,
            vote_count: 1,
          },
          {
            adult: false,
            backdrop_path: "/nbYKGoDpInDPDkWkA2czjPVN6e4.jpg",
            genre_ids: [10749, 18],
            id: 820912,
            original_language: "en",
            original_title: "Persuasion",
            overview:
              "Living with her snobby family on the brink of bankruptcy, Anne Elliot is an unconforming woman with modern sensibilities. When Frederick Wentworth - the dashing one she once sent away - crashes back into her life, Anne must choose between putting the past behind her or listening to her heart when it comes to second chances.",
            popularity: 25.616,
            poster_path: "/s99WrKSEVR4RVvwm5Zn2cqrHTMM.jpg",
            release_date: "2022-07-08",
            title: "Persuasion",
            video: false,
            vote_average: 0,
            vote_count: 0,
          },
          {
            adult: false,
            backdrop_path: "/aSgFDRnfppKxRGZE8BWOfgzAR3k.jpg",
            genre_ids: [28, 53],
            id: 523638,
            original_language: "en",
            original_title: "Prisoners of the Ghostland",
            overview:
              "In the treacherous frontier city of Samurai Town, a ruthless bank robber is sprung from jail by wealthy warlord The Governor, whose adopted granddaughter Bernice has gone missing. The Governor offers the prisoner his freedom in exchange for retrieving the runaway. Strapped into a leather suit that will self-destruct within five days, the bandit sets off on a journey to find the young woman—and his own path to redemption.",
            popularity: 20.326,
            poster_path: "/j5HRzcvN1QXZLvwfc3NLxX8XQJY.jpg",
            release_date: "2021-08-31",
            title: "Prisoners of the Ghostland",
            video: false,
            vote_average: 5,
            vote_count: 306,
          },
          {
            adult: false,
            backdrop_path: "/npEUveGYH2H7VTlM8k6xH6Jcvqr.jpg",
            genre_ids: [18, 36],
            id: 684281,
            original_language: "en",
            original_title: "Adventures of a Mathematician",
            overview:
              "The warmhearted story of Polish immigrant and mathematician Stan Ulam, who moved to the U.S. in the 1930s. Stan deals with the difficult losses of family and friends all while helping to create the hydrogen bomb and the first computer.",
            popularity: 19.014,
            poster_path: "/j2QwbzBQNEw0Wx8ijiCqDZv3TVP.jpg",
            release_date: "2021-06-11",
            title: "Adventures of a Mathematician",
            video: false,
            vote_average: 6.2,
            vote_count: 36,
          },
          {
            adult: false,
            backdrop_path: "/dprG5VW5JAbcGQlsXL74Dj7DRjy.jpg",
            genre_ids: [35, 18],
            id: 668640,
            original_language: "es",
            original_title: "Competencia Oficial",
            overview:
              "When a billionaire entrepreneur impulsively decides to create an iconic movie, he demands the best. Renowned filmmaker Lola Cuevas is recruited to mastermind this ambitious endeavour. Completing the all-star team are two actors with massive talent but even bigger egos: Hollywood heartthrob Félix Rivero and radical theatre actor Iván Torres. Both are legends, but not exactly best friends. Through a series of increasingly eccentric trials set by Lola, Félix and Iván must confront not only each other, but also their own legacies. Who will be left when the cameras finally start rolling?",
            popularity: 18.826,
            poster_path: "/7AQbfQuLvUzKkEUdgwXExZnCJS9.jpg",
            release_date: "2021-09-04",
            title: "Official Competition",
            video: false,
            vote_average: 6.8,
            vote_count: 85,
          },
          {
            adult: false,
            backdrop_path: "/2kj6FOo0B9NtCen1Ta7LoaPW9wG.jpg",
            genre_ids: [18, 878],
            id: 585378,
            original_language: "en",
            original_title: "After Yang",
            overview:
              "When his young daughter's beloved companion — an android named Yang — malfunctions, Jake searches for a way to repair him. In the process, Jake discovers the life that has been passing in front of him, reconnecting with his wife and daughter across a distance he didn't know was there.",
            popularity: 17.759,
            poster_path: "/qjEuDeKOhA7JqaaqhLSfoS9titb.jpg",
            release_date: "2022-03-04",
            title: "After Yang",
            video: false,
            vote_average: 6.8,
            vote_count: 81,
          },
          {
            adult: false,
            backdrop_path: "/jrJqGwW4hxiSUV4Uzbm2Ld3lt2J.jpg",
            genre_ids: [28, 53],
            id: 655302,
            original_language: "fi",
            original_title: "Omerta: 6/12",
            overview:
              "The reception for Finland's Independence Day is rudely interrupted when the presidential palace is attacked and the state leadership is taken hostage. Max Tanner of the Security Police is appointed as a negotiator in the hostage crisis, that unfolds as part of a bigger plan to undermine European security.",
            popularity: 17.63,
            poster_path: "/llItP3ncQG7mTsMXGUvxkDtXkhB.jpg",
            release_date: "2021-11-26",
            title: "Attack on Finland",
            video: false,
            vote_average: 5,
            vote_count: 9,
          },
          {
            adult: false,
            backdrop_path: "/mWS0X8Zs04gwFcoTsgiuEmbFiAZ.jpg",
            genre_ids: [35],
            id: 611408,
            original_language: "fr",
            original_title: "Mystère à Saint-Tropez",
            overview:
              "Every summer, the Billionaire Tranchant and his wife Eliane host the glamorous world of celebrities in their luxurious mansion in the south of France. When a criminal car sabotage related to threatening letters wreak havoc in the villa, Tranchant goes in search of the best agent for the investigation. In the middle of this hot summer, only the arrogant and incompetent agent Boullin is available... To catch the suspect and solve the mystery, he will have no choice but to impersonate a newly hired butler and will turn everyone’s vacation into a hilarious game of ‘Cluedo’!",
            popularity: 16.366,
            poster_path: "/bWpIB5MWhH3vDmNUOC1PuE0ejt1.jpg",
            release_date: "2021-07-14",
            title: "Do You Do You Saint-Tropez",
            video: false,
            vote_average: 5.3,
            vote_count: 83,
          },
          {
            adult: false,
            backdrop_path: "/lRwK3unOv3E14KyEYfeXtBt5fsD.jpg",
            genre_ids: [10749],
            id: 834742,
            original_language: "en",
            original_title: "First Love",
            overview:
              "A young man’s difficult entry into adulthood, who experiences the highs and lows of his first love, while dealing with the familial fallout spurred by the financial crisis of 2008.",
            popularity: 13.999,
            poster_path: "/aygkRhW2pOmJHP8KgU4rVK9gKJb.jpg",
            release_date: "2022-07-07",
            title: "First Love",
            video: false,
            vote_average: 0,
            vote_count: 0,
          },
          {
            adult: false,
            backdrop_path: "/7DBdVT5KEhjnMLpoejbYylfzd92.jpg",
            genre_ids: [16, 28, 80, 9648],
            id: 903939,
            original_language: "ja",
            original_title: "名探偵コナン ハロウィンの花嫁",
            overview: "",
            popularity: 13.742,
            poster_path: "/zhxM93OE09iCjXOuH50dNhoK0zt.jpg",
            release_date: "2022-04-15",
            title: "Detective Conan: The Bride of Halloween",
            video: false,
            vote_average: 6.1,
            vote_count: 13,
          },
        ],
        TopRated: [
          {
            adult: false,
            backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
            genre_ids: [18, 80],
            id: 278,
            original_language: "en",
            original_title: "The Shawshank Redemption",
            overview:
              "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
            popularity: 68.821,
            poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
            release_date: "1994-09-23",
            title: "The Shawshank Redemption",
            video: false,
            vote_average: 8.7,
            vote_count: 21604,
          },
          {
            adult: false,
            backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
            genre_ids: [35, 18, 10749],
            id: 19404,
            original_language: "hi",
            original_title: "दिलवाले दुल्हनिया ले जायेंगे",
            overview:
              "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
            popularity: 25.484,
            poster_path: "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
            release_date: "2007-08-07",
            title: "Dilwale Dulhania Le Jayenge",
            video: false,
            vote_average: 8.7,
            vote_count: 3685,
          },
          {
            adult: false,
            backdrop_path: "/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
            genre_ids: [18, 80],
            id: 238,
            original_language: "en",
            original_title: "The Godfather",
            overview:
              "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
            popularity: 71.613,
            poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
            release_date: "1972-03-14",
            title: "The Godfather",
            video: false,
            vote_average: 8.7,
            vote_count: 16088,
          },
          {
            adult: false,
            backdrop_path: "/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
            genre_ids: [18, 36, 10752],
            id: 424,
            original_language: "en",
            original_title: "Schindler's List",
            overview:
              "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
            popularity: 41.671,
            poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
            release_date: "1993-12-15",
            title: "Schindler's List",
            video: false,
            vote_average: 8.6,
            vote_count: 12859,
          },
          {
            adult: false,
            backdrop_path: "/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg",
            genre_ids: [18, 80],
            id: 240,
            original_language: "en",
            original_title: "The Godfather: Part II",
            overview:
              "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
            popularity: 51.108,
            poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
            release_date: "1974-12-20",
            title: "The Godfather: Part II",
            video: false,
            vote_average: 8.6,
            vote_count: 9705,
          },
          {
            adult: false,
            backdrop_path: "/3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg",
            genre_ids: [10749, 16],
            id: 372754,
            original_language: "ja",
            original_title: "同級生",
            overview:
              "Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school’s upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other’s voice and harmonize, their hearts start to beat together.",
            popularity: 12.698,
            poster_path: "/cIfRCA5wEvj9tApca4UDUagQEiM.jpg",
            release_date: "2016-05-06",
            title: "Dou kyu sei – Classmates",
            video: false,
            vote_average: 8.6,
            vote_count: 233,
          },
          {
            adult: false,
            backdrop_path: "/hZth9NCeXvvO7Xi98d8q34e1Ier.jpg",
            genre_ids: [16, 10751, 14],
            id: 129,
            original_language: "ja",
            original_title: "千と千尋の神隠し",
            overview:
              "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
            popularity: 89.884,
            poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
            release_date: "2002-09-20",
            title: "Spirited Away",
            video: false,
            vote_average: 8.5,
            vote_count: 12942,
          },
          {
            adult: false,
            backdrop_path: "/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg",
            genre_ids: [10749, 16, 18],
            id: 372058,
            original_language: "ja",
            original_title: "君の名は。",
            overview:
              "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
            popularity: 184.822,
            poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
            release_date: "2017-04-07",
            title: "Your Name.",
            video: false,
            vote_average: 8.5,
            vote_count: 8789,
          },
          {
            adult: false,
            backdrop_path: "/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg",
            genre_ids: [10749],
            id: 696374,
            original_language: "en",
            original_title: "Gabriel's Inferno",
            overview:
              "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
            popularity: 12.261,
            poster_path: "/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg",
            release_date: "2020-05-29",
            title: "Gabriel's Inferno",
            video: false,
            vote_average: 8.5,
            vote_count: 2248,
          },
          {
            adult: false,
            backdrop_path: "/lp6SmwyNRspEYkkLXFEVuNlCw77.jpg",
            genre_ids: [16, 14, 10749, 18],
            id: 533514,
            original_language: "ja",
            original_title: "劇場版 ヴァイオレット・エヴァーガーデン",
            overview:
              "As the world moves on from the war and technological advances bring changes to her life, Violet still hopes to see her lost commanding officer again.",
            popularity: 19.631,
            poster_path: "/bajajkoErDst0JxdFyBkABiF9rW.jpg",
            release_date: "2021-03-30",
            title: "Violet Evergarden: The Movie",
            video: false,
            vote_average: 8.5,
            vote_count: 235,
          },
          {
            adult: false,
            backdrop_path: "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
            genre_ids: [35, 53, 18],
            id: 496243,
            original_language: "ko",
            original_title: "기생충",
            overview:
              "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
            popularity: 64.781,
            poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
            release_date: "2019-10-11",
            title: "Parasite",
            video: false,
            vote_average: 8.5,
            vote_count: 13847,
          },
          {
            adult: false,
            backdrop_path: "/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg",
            genre_ids: [10749],
            id: 724089,
            original_language: "en",
            original_title: "Gabriel's Inferno: Part II",
            overview:
              "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
            popularity: 14.183,
            poster_path: "/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg",
            release_date: "2020-07-31",
            title: "Gabriel's Inferno: Part II",
            video: false,
            vote_average: 8.5,
            vote_count: 1413,
          },
          {
            adult: false,
            backdrop_path: "/tj6iPnz18hGfr0LKqWmG6Cp3niO.jpg",
            genre_ids: [18],
            id: 389,
            original_language: "en",
            original_title: "12 Angry Men",
            overview:
              "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
            popularity: 27.716,
            poster_path: "/ppd84D2i9W8jXmsyInGyihiSyqz.jpg",
            release_date: "1957-04-10",
            title: "12 Angry Men",
            video: false,
            vote_average: 8.5,
            vote_count: 6469,
          },
          {
            adult: false,
            backdrop_path: "/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg",
            genre_ids: [14, 18, 80],
            id: 497,
            original_language: "en",
            original_title: "The Green Mile",
            overview:
              "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
            popularity: 65.996,
            poster_path: "/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
            release_date: "1999-12-10",
            title: "The Green Mile",
            video: false,
            vote_average: 8.5,
            vote_count: 14022,
          },
          {
            adult: false,
            backdrop_path: "/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg",
            genre_ids: [10749, 35],
            id: 761053,
            original_language: "en",
            original_title: "Gabriel's Inferno: Part III",
            overview:
              "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.",
            popularity: 31.777,
            poster_path: "/uqmTxOP3gNl5MWRt1wlrUnzTphM.jpg",
            release_date: "2020-11-19",
            title: "Gabriel's Inferno: Part III",
            video: false,
            vote_average: 8.5,
            vote_count: 965,
          },
          {
            adult: false,
            backdrop_path: "/6fA9nie4ROlkyZAUlgKNjGNCbHG.jpg",
            genre_ids: [18, 28, 80, 53],
            id: 155,
            original_language: "en",
            original_title: "The Dark Knight",
            overview:
              "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
            popularity: 70.861,
            poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
            release_date: "2008-07-18",
            title: "The Dark Knight",
            video: false,
            vote_average: 8.5,
            vote_count: 27721,
          },
          {
            adult: false,
            backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
            genre_ids: [53, 80],
            id: 680,
            original_language: "en",
            original_title: "Pulp Fiction",
            overview:
              "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
            popularity: 54.932,
            poster_path: "/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg",
            release_date: "1994-10-14",
            title: "Pulp Fiction",
            video: false,
            vote_average: 8.5,
            vote_count: 23290,
          },
          {
            adult: false,
            backdrop_path: "/x4biAVdPVCghBlsVIzB6NmbghIz.jpg",
            genre_ids: [37],
            id: 429,
            original_language: "it",
            original_title: "Il buono, il brutto, il cattivo",
            overview:
              "While the Civil War rages between the Union and the Confederacy, three men – a quiet loner, a ruthless hit man and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
            popularity: 37.278,
            poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
            release_date: "1967-12-29",
            title: "The Good, the Bad and the Ugly",
            video: false,
            vote_average: 8.5,
            vote_count: 6673,
          },
          {
            adult: false,
            backdrop_path: "/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg",
            genre_ids: [12, 14, 28],
            id: 122,
            original_language: "en",
            original_title: "The Lord of the Rings: The Return of the King",
            overview:
              "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
            popularity: 91.981,
            poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
            release_date: "2003-12-17",
            title: "The Lord of the Rings: The Return of the King",
            video: false,
            vote_average: 8.5,
            vote_count: 19651,
          },
          {
            adult: false,
            backdrop_path: "/qdIMHd4sEfJSckfVJfKQvisL02a.jpg",
            genre_ids: [35, 18, 10749],
            id: 13,
            original_language: "en",
            original_title: "Forrest Gump",
            overview:
              "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
            popularity: 52.357,
            poster_path: "/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
            release_date: "2014-09-05",
            title: "Forrest Gump",
            video: false,
            vote_average: 8.5,
            vote_count: 22832,
          },
        ],
      },
    },
  };
}
